### ISSUE TITLE
raven (Sentry) broken with PLone 5.1.5

### ISSUE THREAD

**Issue by pbauer** [starzel/buildout#43]
Running in Production with Plone 5.1.5 fails with this traceback.
Removing raven woks around that.

```
2019-01-02 16:02:53 INFO Zope Ready to handle requests
2019-01-02 16:03:00 ERROR ZPublisher BeforeTraverse: Error while invoking hook: "acl_users"
Traceback (most recent call last):
  File "/Users/pbauer/.cache/buildout/eggs/Zope2-2.13.27-py2.7.egg/ZPublisher/BeforeTraverse.py", line 143, in __call__
    meth(*(container, request, None)[:args])
TypeError: 'PluggableAuthService' object is not callable
unbound method __repr__() must be called with Application instance as first argument (got nothing instead)
2019-01-02 16:03:00 ERROR sentry.errors.serializer unbound method __repr__() must be called with Application instance as first argument (got nothing instead)
Traceback (most recent call last):
  File "/Users/pbauer/.cache/buildout/eggs/raven-6.9.0-py2.7.egg/raven/utils/serializer/manager.py", line 76, in transform
    return repr(value)
TypeError: unbound method __repr__() must be called with Application instance as first argument (got nothing instead)
unbound method __repr__() must be called with Application instance as first argument (got nothing instead)
2019-01-02 16:03:00 ERROR sentry.errors.serializer unbound method __repr__() must be called with Application instance as first argument (got nothing instead)
Traceback (most recent call last):
  File "/Users/pbauer/.cache/buildout/eggs/raven-6.9.0-py2.7.egg/raven/utils/serializer/manager.py", line 76, in transform
    return repr(value)
TypeError: unbound method __repr__() must be called with Application instance as first argument (got nothing instead)
2019-01-02 16:03:00 ERROR Zope.SiteErrorLog 1546441380.250.259841875655 http://localhost:8080/index_html
Traceback (innermost last):
  Module ZPublisher.Publish, line 127, in publish
  Module ZPublisher.BaseRequest, line 605, in traverse
  Module ZPublisher.BaseRequest, line 710, in old_validation
TypeError: 'PluggableAuthService' object is not iterable
Traceback (most recent call last):
  File "/Users/pbauer/.cache/buildout/eggs/Zope2-2.13.27-py2.7.egg/ZPublisher/Publish.py", line 127, in publish
    object=request.traverse(path, validated_hook=validated_hook)
  File "/Users/pbauer/.cache/buildout/eggs/Zope2-2.13.27-py2.7.egg/ZPublisher/BaseRequest.py", line 605, in traverse
    user=old_validation(groups, request, auth, self.roles)
  File "/Users/pbauer/.cache/buildout/eggs/Zope2-2.13.27-py2.7.egg/ZPublisher/BaseRequest.py", line 710, in old_validation
    for d in groups:
TypeError: 'PluggableAuthService' object is not iterable
```

**Comment by pbauer** [comment]
Fixed with https://github.com/starzel/buildout/commit/c4f765dc4e4a6532c2bb10b1ef355ee283055b8f

The reason for the issue was not raven but a problem withou the way that inheritance worked in the starzel buildout.
There was is a counterintuitive interaction between <= and +=.
E.g. adding a egg in zeoclient1 with += effectively deletes all inherited eggs (with <=) from instance_base.
The order of evaluating <= and += is so that zeoclient1 would collect a list of eggs while overlaying the all the config-files, which then overrides the eggs-list from instance_base.

For future reference: do not use <= in the starzel buildout.
